#!/bin/bash

CONFIG_FILE="src/config.h"

# Ensure directory exists
mkdir -p "$(dirname "$CONFIG_FILE")"

echo "=== Configuration Setup ==="

# Prompt user for values
read -p "Enter WiFi SSID: " WIFI_SSID
read -sp "Enter WiFi Password: " WIFI_PASSWORD
echo
read -p "Enter API Key: " API_KEY

# Overwrite config.h with new definitions
cat > "$CONFIG_FILE" <<EOF
#pragma once

// --- Auto-generated configuration ---
// Do not edit manually; this file is generated by setup_config.sh

#define LATITUDE   49.28   // Vancouver
#define LONGITUDE -123.12

#define WIFI_SSID      "$WIFI_SSID"
#define WIFI_PASSWORD  "$WIFI_PASSWORD"
#define API_KEY        "$API_KEY"

EOF

echo "Configuration file created at $CONFIG_FILE"
